version: 1.0.{build}
branches:
  only:
  - trigger-appveyor/*
image: Visual Studio 2017
init:
- cmd: wmic os get osarchitecture
build_script:
- cmd: >-
    dotnet --version

    dotnet restore ./implementation/PersistentProcess/PersistentProcess.Common/PersistentProcess.Common.csproj --verbosity m

    dotnet publish ./implementation/PersistentProcess/PersistentProcess.Common/PersistentProcess.Common.csproj
test_script:
- cmd: >-
    dotnet restore ./implementation/PersistentProcess/PersistentProcess.Test/PersistentProcess.Test.csproj --verbosity m

    cd implementation/PersistentProcess/PersistentProcess.Test

    dotnet test --test-adapter-path:. --logger:Appveyor