# Script for Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines

trigger:
- master

pool:
  vmImage: $(vmImage)

steps:
- script: |
    echo my vmImage is $(vmImage)

- task: DotNetCoreInstaller@0
  inputs:
    packageType: 'sdk' # Options: runtime, sdk
    version: '2.2.104' 

- script: dotnet --version

- script: dotnet test ./implementation/PersistentProcess/PersistentProcess.Test/PersistentProcess.Test.csproj --logger trx
  displayName: 'test'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- script: dotnet publish ./implementation/PersistentProcess/PersistentProcess.WebHost/PersistentProcess.WebHost.csproj
  displayName: 'publish web host'
