name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/setup-dotnet@v1.2.0
      with:
        dotnet-version: '3.0.100'
    - name: Try use dotnet core 3
      run: dotnet --info
    - uses: actions/checkout@v1
    - name: Run tests
      run: dotnet test ./implement/PersistentProcess/PersistentProcess.Test/PersistentProcess.Test.csproj --logger trx
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
