name: test

on: [push]

jobs:
  build:

    strategy:
      matrix:
        environment: [ubuntu-18.04,windows-2019]

    runs-on: ${{ matrix.environment }}

    steps:
    - uses: actions/setup-dotnet@v1.2.0
      with:
        dotnet-version: '3.1.100'
    - name: Try use dotnet core 3
      run: dotnet --info
    - uses: actions/checkout@v1
    - name: Run tests
      run: dotnet test ./implement/PersistentProcess/PersistentProcess.Test/PersistentProcess.Test.csproj --logger trx
